<?php
/**
 * Copyright (c) 2021. All rights reserved ePay Payment Solutions.
 *
 * This program is free software. You are allowed to use the software but NOT allowed to modify the software.
 * It is also not legal to do any changes to the software and distribute it in your own name / brand.
 *
 * All use of the payment modules happens at your own risk. We offer a free test account that you can use to test the module.
 *
 * @author    ePay Payment Solutions
 * @copyright ePay Payment Solutions (https://epay.dk)
 * @license   ePay Payment Solutions
 *
 */

?>
<div>
    <br/>
    <table class="epay_action_container" border="0" width="100%">

        <?php
        echo $block->getTransactionData(); ?>

    </table>
    <br/> <br/>
    <table class="epay_transaction_history_container" border="0" width="100%">

        <?php
        echo $block->getTransactionLogData(); ?>

    </table>

</div>
